spring:
  jackson:
     deserialization:
        UNWRAP_ROOT_VALUE: true
image:
  default: https://static.productionready.io/images/smiley-cyrus.jpg
jwt:
  secret: nRvyYC4soFxBdZ-F-5Nnzz5USXstR1YylsTd-mA0aKtI9HUlriGrtkf-TiuDapkLiUCogO3JOK7kwZisrHp6wA
  sessionTime: 86400
mybatis:
  configuration:
    cache-enabled: true
    default-statement-timeout: 3000
    map-underscore-to-camel-case: true
    use-generated-keys: true
  type-handlers-package: io.spring.infrastructure.mybatis
  mapper-locations: 'mapper/*.xml'

logging:
  level:
    ROOT: INFO
    io.spring.infrastructure.mybatis.readservice.ArticleReadService: DEBUG
    com:
      ROOT: INFO
      corelogic: DEBUG
      google: DEBUG
    org:
      apache: INFO
      springframework: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: FULL
